const isRealMedia=v=>typeof v==='string'&&v.trim()&&!/images\.unsplash\.com/i.test(v);
const setText=(root,selector,value)=>{const el=root?.querySelector(selector);if(el&&value!==undefined)el.textContent=value||''};
const replacePlaceholder=(root,url,alt='')=>{if(!root||!isRealMedia(url))return;let img=root.querySelector('img.cms-image');const ph=root.querySelector('.photo-placeholder');if(!img){img=document.createElement('img');img.className='cms-image';img.style.cssText='width:100%;height:100%;min-height:185px;object-fit:cover;display:block';if(ph)ph.replaceWith(img);else root.prepend(img)}img.src=url;img.alt=alt};
async function applyCms(){try{const r=await fetch('/api/content',{cache:'no-store'});if(!r.ok)return;const c=await r.json();if(!c)return;
 const hero=document.querySelector('.hero');if(hero&&isRealMedia(c.hero?.image)){hero.style.background=`linear-gradient(90deg,rgba(12,24,19,.78),rgba(12,24,19,.18)),url("${c.hero.image}") center/cover no-repeat`;hero.classList.remove('hero-empty');document.querySelector('.hero-upload-note')?.remove()}if(hero&&c.hero){setText(hero,'.kicker',c.hero.eyebrow);const h=hero.querySelector('h1');if(h)h.innerHTML=String(c.hero.title||'').replace(/\n/g,'<br/>');setText(hero,'p:not(.kicker)',c.hero.body)}
 const proof=document.querySelector('.proof');if(proof&&c.proof){setText(proof,'.section-title h2',c.proof.heading);setText(proof,'.section-title p',c.proof.subheading);setText(proof,'blockquote',c.proof.quote);const cards=[...proof.querySelectorAll('article')];(c.proof.properties||[]).forEach((p,i)=>{const card=cards[i];if(!card)return;replacePlaceholder(card,p.image,p.name);setText(card,'h3',p.name);setText(card,'small',p.type);setText(card,'p',p.body)})}
 const system=document.querySelector('.system');if(system&&c.system){const h=system.querySelector('h2');if(h)h.innerHTML=String(c.system.heading||'').replace(/\n/g,'<br/>');replacePlaceholder(system,c.system.image,'AMUMA living')}
 const investment=document.querySelector('.investmentModel');if(investment&&c.investment){setText(investment,'h2',c.investment.heading);setText(investment,'.disclaimer',c.investment.disclaimer);if(isRealMedia(c.investment.image)){investment.style.setProperty('--cms-investment-image',`url("${c.investment.image}")`)}}
 const meaning=document.querySelector('.meaning');if(meaning&&c.about){setText(meaning,'h2',c.about.heading);setText(meaning,'p',c.about.body)}
 const closing=document.querySelector('.closing');if(closing&&c.footer){const h=closing.querySelector('h2');if(h)h.innerHTML=String(c.footer.heading||'').replace(/\n/g,'<br/>');setText(closing,'p',c.footer.body);const copyright=closing.querySelector('.footer small');if(copyright)copyright.textContent=c.footer.copyright||''}
}catch(e){console.error('AMUMA CMS load failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(applyCms,50));else setTimeout(applyCms,50);
